using Newtonsoft.Json;
using Siemens.Engineering.SW.Blocks;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Xml;
using TIAgenerator.Class;

namespace TIAgenerator
{
    //Methods for the generation of Networks to be merge in the main .XML file for the standard PLC part
    //Each Networks is generated by fetching data from the Json objects
    public class XmlGen
    {
        public static void FC_DI_Network(int ID, string nameDB, ref string xml, DigitalSignal signal)
        {
            XmlDocument doc = new XmlDocument();//create empty virtual XmlDoc
            XmlNode node;
            XmlNamespaceManager ns = new XmlNamespaceManager(doc.NameTable); //create namespace manager to use if necessary
            ns.AddNamespace("ns", "http://www.siemens.com/automation/Openness/SW/NetworkSource/FlgNet/v4"); //Add namespace for Node reference if necessary in XML file
            doc.Load(Methods.GetRelativePath(@"\Files\Xml\FC_DI_Network.xml")); //load doc from file
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit"); //pointer to a specific Node
            node.Attributes["ID"].Value = ID.ToString(); //change value of a specific Node's Attibute 
            node = doc.SelectSingleNode("//ns:Component", ns);
            node.Attributes["Name"].Value = signal.tag + "_FLD";
            node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[1]", ns);
            node.Attributes["Name"].Value = nameDB;
            node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[2]", ns);
            node.Attributes["Name"].Value = signal.tag;
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]");
            node.Attributes["ID"].Value = "A" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]//MultilingualTextItem");
            node.Attributes["ID"].Value = "B" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]");
            node.Attributes["ID"].Value = "C" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem");
            node.Attributes["ID"].Value = "D" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem//Text");
            node.InnerText = signal.description; //change text between XML Tag
            xml += "\n" + doc.OuterXml;
        }

        public static void FC_DI_NetworkR(int ID, string nameDB, ref string xml, DigitalSignal signal)
        {
            XmlDocument doc = new XmlDocument();                                                                        //create empty virtual XmlDoc
            XmlNode node;
            XmlNamespaceManager ns = new XmlNamespaceManager(doc.NameTable);                                            //create namespace manager to use if necessary
            ns.AddNamespace("ns", "http://www.siemens.com/automation/Openness/SW/NetworkSource/FlgNet/v4");             //Add namespace for Node reference if necessary in XML file
            doc.Load(Methods.GetRelativePath(@"\Files\Xml\FC_DI_NetworkR.xml"));                                                       //load doc from file
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit");                                             //pointer to a specific Node
            node.Attributes["ID"].Value = ID.ToString();                                                                //change value of a specific Node's Attibute 
            node = doc.SelectSingleNode("//ns:Component", ns);
            node.Attributes["Name"].Value = signal.tag + "_FLD";
            node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[1]", ns);
            node.Attributes["Name"].Value = signal.tag + "_FLDR";
            node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[1]", ns);
            node.Attributes["Name"].Value = nameDB;
            node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[2]", ns);
            node.Attributes["Name"].Value = signal.tag;
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]");
            node.Attributes["ID"].Value = "A" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]//MultilingualTextItem");
            node.Attributes["ID"].Value = "B" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]");
            node.Attributes["ID"].Value = "C" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem");
            node.Attributes["ID"].Value = "D" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem//Text");
            node.InnerText = signal.description;                                                                             //change text between XML Tag
            xml += "\n" + doc.OuterXml;
        }

        public static void FC_DI_NetworkAT(ConfigSettings settings, int ID, ref string xml, DigitalSignal signal)
        {
            XmlDocument doc = new XmlDocument();                                                                        //create empty virtual XmlDoc
            XmlNode node;
            XmlNamespaceManager ns = new XmlNamespaceManager(doc.NameTable);                                            //create namespace manager to use if necessary
            ns.AddNamespace("ns", "http://www.siemens.com/automation/Openness/SW/NetworkSource/FlgNet/v4");             //Add namespace for Node reference if necessary in XML file
            doc.Load(Methods.GetRelativePath(@"\Files\Xml\FC_DI_Network_AT.xml"));                                                       //load doc from file
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit");                                             //pointer to a specific Node
            node.Attributes["ID"].Value = ID.ToString();
            node = doc.SelectSingleNode("//ns:Access[1]//ns:Component", ns);
            node.Attributes["Name"].Value = signal.tag + "_FLD";
            node = doc.SelectSingleNode("//ns:Access[2]//ns:Component", ns);
            node.Attributes["Name"].Value = settings.tagReset;
            node = doc.SelectSingleNode("//ns:Access[3]//ns:ConstantValue", ns);
            node.InnerText = "false";
            node = doc.SelectSingleNode("//ns:Access[4]//ns:ConstantValue", ns);
            node.InnerText = "false";
            node = doc.SelectSingleNode("//ns:Access[5]//ns:ConstantValue", ns);
            node.InnerText = "t#1s";
            node = doc.SelectSingleNode("//ns:Access[6]//ns:ConstantValue", ns);
            node.InnerText = signal.isTrip;
            node = doc.SelectSingleNode("//ns:Access[7]//ns:ConstantValue", ns);
            node.InnerText = "false";
            node = doc.SelectSingleNode("//ns:Access[8]//ns:Component[1]", ns);
            node.Attributes["Name"].Value = "UP";
            node = doc.SelectSingleNode("//ns:Access[8]//ns:Component[2]", ns);
            node.Attributes["Name"].Value = settings.tagTripFlash;
            node = doc.SelectSingleNode("//ns:Access[9]//ns:Component[1]", ns);
            node.Attributes["Name"].Value = "UP";
            node = doc.SelectSingleNode("//ns:Access[9]//ns:Component[2]", ns);
            node.Attributes["Name"].Value = settings.tagAlmFlash;
            node = doc.SelectSingleNode("//ns:Access[10]//ns:Component", ns);
            node.Attributes["Name"].Value = settings.tagCmnFo;
            node = doc.SelectSingleNode("//ns:Call//ns:Component", ns);
            node.Attributes["Name"].Value = signal.tag;
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]");
            node.Attributes["ID"].Value = "A" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]//MultilingualTextItem");
            node.Attributes["ID"].Value = "B" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]");
            node.Attributes["ID"].Value = "C" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem");
            node.Attributes["ID"].Value = "D" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem//Text");
            node.InnerText = signal.description;                                                                             //change text between XML Tag
            xml += "\n" + doc.OuterXml;
        }

        public static void FC_DI_NetworkATR(ConfigSettings settings, int ID, ref string xml, DigitalSignal signal)
        {
            XmlDocument doc = new XmlDocument();                                                                        //create empty virtual XmlDoc
            XmlNode node;
            XmlNamespaceManager ns = new XmlNamespaceManager(doc.NameTable);                                            //create namespace manager to use if necessary
            ns.AddNamespace("ns", "http://www.siemens.com/automation/Openness/SW/NetworkSource/FlgNet/v4");             //Add namespace for Node reference if necessary in XML file
            doc.Load(Methods.GetRelativePath(@"\Files\Xml\FC_DI_Network_ATR.xml"));                                                       //load doc from file
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit");                                             //pointer to a specific Node
            node.Attributes["ID"].Value = ID.ToString();
            node = doc.SelectSingleNode("//ns:Access[1]//ns:Component", ns);
            node.Attributes["Name"].Value = signal.tag + "_FLD";
            node = doc.SelectSingleNode("//ns:Access[2]//ns:Component", ns);
            node.Attributes["Name"].Value = signal.tag + "_FLDR";
            node = doc.SelectSingleNode("//ns:Access[3]//ns:Component", ns);
            node.Attributes["Name"].Value = settings.tagReset;
            node = doc.SelectSingleNode("//ns:Access[4]//ns:ConstantValue", ns);
            node.InnerText = "false";
            node = doc.SelectSingleNode("//ns:Access[5]//ns:ConstantValue", ns);
            node.InnerText = "false";
            node = doc.SelectSingleNode("//ns:Access[6]//ns:ConstantValue", ns);
            node.InnerText = "t#1s";
            node = doc.SelectSingleNode("//ns:Access[7]//ns:ConstantValue", ns);
            node.InnerText = signal.isTrip;
            node = doc.SelectSingleNode("//ns:Access[8]//ns:ConstantValue", ns);
            node.InnerText = "false";
            node = doc.SelectSingleNode("//ns:Access[9]//ns:Component[1]", ns);
            node.Attributes["Name"].Value = "UP";
            node = doc.SelectSingleNode("//ns:Access[9]//ns:Component[2]", ns);
            node.Attributes["Name"].Value = settings.tagTripFlash;
            node = doc.SelectSingleNode("//ns:Access[10]//ns:Component[1]", ns);
            node.Attributes["Name"].Value = "UP";
            node = doc.SelectSingleNode("//ns:Access[10]//ns:Component[2]", ns);
            node.Attributes["Name"].Value = settings.tagAlmFlash;
            node = doc.SelectSingleNode("//ns:Access[11]//ns:Component", ns);
            node.Attributes["Name"].Value = settings.tagCmnFo;
            node = doc.SelectSingleNode("//ns:Call//ns:Component", ns);
            node.Attributes["Name"].Value = signal.tag;
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]");
            node.Attributes["ID"].Value = "A" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]//MultilingualTextItem");
            node.Attributes["ID"].Value = "B" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]");
            node.Attributes["ID"].Value = "C" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem");
            node.Attributes["ID"].Value = "D" + ID.ToString();
            node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem//Text");
            node.InnerText = signal.description;                                                                             //change text between XML Tag
            xml += "\n" + doc.OuterXml;
        }

        public static void DB_SettingsBody(ref string xml, AnalogSignal signal)
        {
            XmlDocument doc = new XmlDocument();                                                                        //create empty virtual XmlDoc
            XmlNode node;
            XmlNamespaceManager ns = new XmlNamespaceManager(doc.NameTable);                                            //create namespace manager to use if necessary
            ns.AddNamespace("ns", "");             //Add namespace for Node reference if necessary in XML file
            doc.Load(Methods.GetRelativePath(@"\Files\Xml\DB_SettingsBody.xml"));                                                       //load doc from file                                                            //change value of a specific Node's Attibute 
            node = doc.SelectSingleNode("//ns:Member", ns);
            node.Attributes["Name"].Value = signal.tag;
            node = doc.SelectSingleNode("//ns:Member//ns:MultiLanguageText", ns);
            node.InnerText = signal.description;
            node = doc.SelectSingleNode("//ns:Member//ns:Member[1]//ns:StartValue", ns);
            node.InnerText = signal.minRange;
            node = doc.SelectSingleNode("//ns:Member//ns:Member[2]//ns:StartValue", ns);
            node.InnerText = signal.maxRange;
            node = doc.SelectSingleNode("//ns:Member//ns:Member[3]//ns:StartValue", ns);
            node.InnerText = signal.LoLoSP;
            node = doc.SelectSingleNode("//ns:Member//ns:Member[4]//ns:StartValue", ns);
            node.InnerText = signal.LoSP;
            node = doc.SelectSingleNode("//ns:Member//ns:Member[5]//ns:StartValue", ns);
            node.InnerText = signal.HiSP;
            node = doc.SelectSingleNode("//ns:Member//ns:Member[6]//ns:StartValue", ns);
            node.InnerText = signal.HiHiSP;
            xml += "\n" + doc.OuterXml;
        }

        public static void FC_AIn_Network(ConfigSettings settings, int ID, ref string xml, AnalogSignal signal)
        {

            XmlDocument doc = new XmlDocument();                                                                        //create empty virtual XmlDoc
            XmlNode node;
            XmlNamespaceManager ns = new XmlNamespaceManager(doc.NameTable);                                            //create namespace manager to use if necessary
            ns.AddNamespace("ns", "http://www.siemens.com/automation/Openness/SW/NetworkSource/FlgNet/v4");             //Add namespace for Node reference if necessary in XML file
            doc.Load(Methods.GetRelativePath(@"\Files\Xml\FC_AIn_Network.xml"));                                           //load doc from file                                                            //change value of a specific Node's Attibute 
            if (signal.isRedundant == "false")
            {
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit");                                             //pointer to a specific Node
                node.Attributes["ID"].Value = ID.ToString();
                node = doc.SelectSingleNode("//ns:Access[1]//ns:Component[1]", ns);//inp_PV
                node.Attributes["Name"].Value = signal.tag + "_FLD";
                node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[1]", ns);//cfg_PVEUMin
                node.Attributes["Name"].Value = "SETTINGS";
                node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "RANGE_L";
                node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[1]", ns); //cfg_PVEUMax
                node.Attributes["Name"].Value = "SETTINGS";;
                node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "RANGE_H";
                node = doc.SelectSingleNode("//ns:Access[18]//ns:Component[1]", ns);//oset_HiHiLim
                node.Attributes["Name"].Value = "SETTINGS";;
                node = doc.SelectSingleNode("//ns:Access[18]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[18]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "SP_HH";
                node = doc.SelectSingleNode("//ns:Access[25]//ns:Component[1]", ns);//oset_HiLim
                node.Attributes["Name"].Value = "SETTINGS";;
                node = doc.SelectSingleNode("//ns:Access[25]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[25]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "SP_H";
                node = doc.SelectSingleNode("//ns:Access[31]//ns:Component[1]", ns);//oset_LoLim
                node.Attributes["Name"].Value = "SETTINGS";;
                node = doc.SelectSingleNode("//ns:Access[31]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[31]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "SP_L";
                node = doc.SelectSingleNode("//ns:Access[37]//ns:Component[1]", ns);//oset_LoLoLim
                node.Attributes["Name"].Value = "SETTINGS";;
                node = doc.SelectSingleNode("//ns:Access[37]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[37]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "SP_LL";
                node = doc.SelectSingleNode("//ns:Access[4]//ns:ConstantValue", ns);
                node.InnerText = "0";
                node = doc.SelectSingleNode("//ns:Access[5]//ns:ConstantValue", ns);
                node.InnerText = "27648";
                node = doc.SelectSingleNode("//ns:Access[6]//ns:ConstantValue", ns);
                node.InnerText = "29376";
                node = doc.SelectSingleNode("//ns:Access[7]//ns:ConstantValue", ns);
                node.InnerText = "-691";
                node = doc.SelectSingleNode("//ns:Access[10]//ns:ConstantValue", ns);//cfg_FailTripsUnit
                node.InnerText = signal.FailTrips;
                node = doc.SelectSingleNode("//ns:Access[14]//ns:Component[1]", ns);//cfg_InFailUseValSub
                node.Attributes["Name"].Value = "false";
                node = doc.SelectSingleNode("//ns:Access[15]//ns:ConstantValue", ns);//cfg_ValSub
                node.InnerText = "0.0";
                node = doc.SelectSingleNode("//ns:Access[43]//ns:Component[1]", ns);//inp_Reset
                node.Attributes["Name"].Value = settings.tagReset;
                node = doc.SelectSingleNode("//ns:Access[47]//ns:Component[1]", ns);//commonFirstOut
                node.Attributes["Name"].Value = settings.tagCmnFo;
                node = doc.SelectSingleNode("//ns:Access[48]//ns:Component[1]", ns);//isaAlarmFlashing
                node.Attributes["Name"].Value = "UP";
                node = doc.SelectSingleNode("//ns:Access[48]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = settings.tagAlmFlash;
                node = doc.SelectSingleNode("//ns:Access[49]//ns:Component[1]", ns);//isaTripsFlashing
                node.Attributes["Name"].Value = "UP";
                node = doc.SelectSingleNode("//ns:Access[49]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = settings.tagTripFlash;

                if(signal.hasHiHi == "true" || (signal.hasHi == "true" && signal.hasLoLo == "false"))
                {
                    node = doc.SelectSingleNode("//ns:Access[12]//ns:Component[1]", ns);//cfg_InFailUsePVEUMax
                    node.Attributes["Name"].Value = "true";
                }
                else
                {
                    node = doc.SelectSingleNode("//ns:Access[12]//ns:Component[1]", ns);
                    node.Attributes["Name"].Value = "false";
                }

                if (!(signal.hasHiHi == "true" || (signal.hasHi == "true" && signal.hasLoLo == "false")))
                {
                    node = doc.SelectSingleNode("//ns:Access[13]//ns:Component[1]", ns);//cfg_InFailUsePVEUMin
                    node.Attributes["Name"].Value = "true";
                }
                else
                {
                    node = doc.SelectSingleNode("//ns:Access[13]//ns:Component[1]", ns);
                    node.Attributes["Name"].Value = "false";
                }

                if (signal.description.ToLower().Contains("temperature"))
                {
                    node = doc.SelectSingleNode("//ns:Access[19]//ns:ConstantValue", ns);//cfg_HiHiDelay
                    node.InnerText = "T#5s";
                    node = doc.SelectSingleNode("//ns:Access[26]//ns:ConstantValue", ns);//cfg_HiDelay
                    node.InnerText = "T#5s";
                    node = doc.SelectSingleNode("//ns:Access[32]//ns:ConstantValue", ns);//cfg_LoDelay
                    node.InnerText = "T#5s";
                    node = doc.SelectSingleNode("//ns:Access[38]//ns:ConstantValue", ns);//cfg_LoLoDelay
                    node.InnerText = "T#5s";
                }
                else
                {
                    node = doc.SelectSingleNode("//ns:Access[19]//ns:ConstantValue", ns);//cfg_HiHiDelay
                    node.InnerText = "T#1s";
                    node = doc.SelectSingleNode("//ns:Access[26]//ns:ConstantValue", ns);//cfg_HiDelay
                    node.InnerText = "T#1s";
                    node = doc.SelectSingleNode("//ns:Access[32]//ns:ConstantValue", ns);//cfg_LoDelay
                    node.InnerText = "T#1s";
                    node = doc.SelectSingleNode("//ns:Access[38]//ns:ConstantValue", ns);//cfg_LoLoDelay
                    node.InnerText = "T#1s";
                }

                if (signal.FailTrips == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[10]//ns:ConstantValue", ns);//cfg_FailTripsUnit
                    node.InnerText = "true";
                }
                if (signal.HiHiTrips == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[22]//ns:ConstantValue", ns);//cfg_HiHiTripsUnit
                    node.InnerText = "true";
                }
                if (signal.LoLoTrips == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[41]//ns:ConstantValue", ns);//cfg_LoLoTripsUnit
                    node.InnerText = "true";
                }

                //VOTING
                if (signal.is1oo2Member == "true" || signal.is2oo2Member == "true" || signal.is2oo3Member == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[1]", ns);//cfg_PVEUMin
                    node.Attributes["Name"].Value = "SETTINGS"; ;
                    node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[2]", ns);
                    node.Attributes["Name"].Value = signal.tagVooting;
                    node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[3]", ns);
                    node.Attributes["Name"].Value = "RANGE_H";
                    node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[1]", ns); //cfg_PVEUMax
                    node.Attributes["Name"].Value = "SETTINGS"; ;
                    node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[2]", ns);
                    node.Attributes["Name"].Value = signal.tagVooting;
                    node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[3]", ns);
                    node.Attributes["Name"].Value = "RANGE_L";
                    node = doc.SelectSingleNode("//ns:Access[18]//ns:Component[1]", ns);//oset_HiHiLim
                    node.Attributes["Name"].Value = "SETTINGS"; ;
                    node = doc.SelectSingleNode("//ns:Access[18]//ns:Component[2]", ns);
                    node.Attributes["Name"].Value = signal.tagVooting;
                    node = doc.SelectSingleNode("//ns:Access[18]//ns:Component[3]", ns);
                    node.Attributes["Name"].Value = "SP_HH";
                    node = doc.SelectSingleNode("//ns:Access[25]//ns:Component[1]", ns);//oset_HiLim
                    node.Attributes["Name"].Value = "SETTINGS"; ;
                    node = doc.SelectSingleNode("//ns:Access[25]//ns:Component[2]", ns);
                    node.Attributes["Name"].Value = signal.tagVooting;
                    node = doc.SelectSingleNode("//ns:Access[25]//ns:Component[3]", ns);
                    node.Attributes["Name"].Value = "SP_H";
                    node = doc.SelectSingleNode("//ns:Access[31]//ns:Component[1]", ns);//oset_LoLim
                    node.Attributes["Name"].Value = "SETTINGS"; ;
                    node = doc.SelectSingleNode("//ns:Access[31]//ns:Component[2]", ns);
                    node.Attributes["Name"].Value = signal.tagVooting;
                    node = doc.SelectSingleNode("//ns:Access[31]//ns:Component[3]", ns);
                    node.Attributes["Name"].Value = "SP_L";
                    node = doc.SelectSingleNode("//ns:Access[37]//ns:Component[1]", ns);//oset_LoLoLim
                    node.Attributes["Name"].Value = "SETTINGS"; ;
                    node = doc.SelectSingleNode("//ns:Access[37]//ns:Component[2]", ns);
                    node.Attributes["Name"].Value = signal.tagVooting;
                    node = doc.SelectSingleNode("//ns:Access[37]//ns:Component[3]", ns);
                    node.Attributes["Name"].Value = "SP_LL";
                    node = doc.SelectSingleNode("//ns:Access[12]//ns:Component[1]", ns);//cfg_InFailUsePVEUMax
                    node.Attributes["Name"].Value = signal.tagVooting;
                    Data.AddChildXML(doc, ns, "//ns:Access[12]//ns:Symbol[1]", "Component", "Name", "Cfg_InFailUsePVEUMax");
                    node = doc.SelectSingleNode("//ns:Access[13]//ns:Component[1]", ns);//cfg_InFailUsePVEUMin
                    node.Attributes["Name"].Value = signal.tagVooting;
                    Data.AddChildXML(doc, ns, "//ns:Access[13]//ns:Symbol[1]", "Component", "Name", "Cfg_InFailUsePVEUMin");
                    node = doc.SelectSingleNode("//ns:Access[14]//ns:Component[1]", ns);//cfg_InFailUseValSub
                    node.Attributes["Name"].Value = signal.tagVooting;
                    Data.AddChildXML(doc, ns, "//ns:Access[14]//ns:Symbol[1]", "Component", "Name", "Cfg_InFailUseValSub");
                    /*
                    node = doc.SelectSingleNode("//ns:Access[15]//ns:Component[1]", ns);//cfg_ValSub
                    node.Attributes["Name"].Value = signal.tagVooting;
                    XmlData.AddChildXML(doc, ns, "//ns:Access[15]//ns:Symbol[1]", "Component", "Name", "Cfg_ValSub");
                    */
                    node = doc.SelectSingleNode("//ns:Access[17]//ns:Component[1]", ns);//cfg_HasHiHiAlm
                    node.Attributes["Name"].Value = signal.tagVooting;
                    Data.AddChildXML(doc, ns, "//ns:Access[17]//ns:Symbol[1]", "Component", "Name", "Cfg_HasHiHiAlm");
                    node = doc.SelectSingleNode("//ns:Access[24]//ns:Component[1]", ns);//cfg_HasHiAlm
                    node.Attributes["Name"].Value = signal.tagVooting;
                    Data.AddChildXML(doc, ns, "//ns:Access[24]//ns:Symbol[1]", "Component", "Name", "Cfg_HasHiAlm");
                    node = doc.SelectSingleNode("//ns:Access[30]//ns:Component[1]", ns);//cfg_HasLoAlm
                    node.Attributes["Name"].Value = signal.tagVooting;
                    Data.AddChildXML(doc, ns, "//ns:Access[30]//ns:Symbol[1]", "Component", "Name", "Cfg_HasLoAlm");
                    node = doc.SelectSingleNode("//ns:Access[36]//ns:Component[1]", ns);//cfg_HasLoLoAlm
                    node.Attributes["Name"].Value = signal.tagVooting;
                    Data.AddChildXML(doc, ns, "//ns:Access[36]//ns:Symbol[1]", "Component", "Name", "Cfg_HasLoLoAlm");
                }
                else
                {
                    if (signal.hasHiHi == "true")
                    {
                        node = doc.SelectSingleNode("//ns:Access[17]//ns:Component[1]", ns);//cfg_HasHiHiAlm
                        node.Attributes["Name"].Value = "true";
                    }
                    if (signal.hasHi == "true")
                    {
                        node = doc.SelectSingleNode("//ns:Access[24]//ns:Component[1]", ns);//cfg_HasHiAlm
                        node.Attributes["Name"].Value = "true";
                    }
                    if (signal.hasLo == "true")
                    {
                        node = doc.SelectSingleNode("//ns:Access[30]//ns:Component[1]", ns);//cfg_HasLoAlm
                        node.Attributes["Name"].Value = "true";
                    }
                    if (signal.hasLoLo == "true")
                    {
                        node = doc.SelectSingleNode("//ns:Access[36]//ns:Component[1]", ns);//cfg_HasLoLoAlm
                        node.Attributes["Name"].Value = "true";
                    }
                }
                
                //NETWORK FOOTER
                node = doc.SelectSingleNode("//ns:Call//ns:Component", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]");
                node.Attributes["ID"].Value = "A" + ID.ToString();
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]//MultilingualTextItem");
                node.Attributes["ID"].Value = "B" + ID.ToString();
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]");
                node.Attributes["ID"].Value = "C" + ID.ToString();
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem");
                node.Attributes["ID"].Value = "D" + ID.ToString();
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem//Text");
                node.InnerText = signal.description;

            }
            string txt = doc.OuterXml;
            //questa parte è temporanea, se si trova un metodo migliore per cfg_ValSub va eliminato AL MOMENTO NON FUNZIONA
            if (signal.is1oo2Member == "true" || signal.is2oo2Member == "true" || signal.is2oo3Member == "true")
            {
                //node.SelectNodes()
                //Console.WriteLine("xml");
                txt = txt.Replace("<Access Scope=\"LiteralConstant\" UId=\"35\">\r\n\t\t\t\t\t\t\t\t\t<Constant>\r\n\t\t\t\t\t\t\t\t\t\t<ConstantType>Real</ConstantType>\r\n\t\t\t\t\t\t\t\t\t\t<ConstantValue>0.0</ConstantValue>\r\n\t\t\t\t\t\t\t\t\t</Constant>\r\n\t\t\t\t\t\t\t\t</Access>", "<Access Scope=\"GlobalVariable\" UId=\"35\">\r\n      <Symbol>\r\n        <Component Name=\"UP\" />\r\n        <Component Name=\"ALM_FLASHING\" />\r\n      </Symbol>\r\n    </Access>");
            }
            xml += "\n" + txt;
        }

        public static void FC_AIn2oo3_Network(ConfigSettings settings, int ID, ref string xml, AnalogSignal ai)
        {            
            AnalogInput2oo3 signal = (AnalogInput2oo3)ai;
            XmlDocument doc = new XmlDocument();                                                                        //create empty virtual XmlDoc
            XmlNode node;
            XmlNamespaceManager ns = new XmlNamespaceManager(doc.NameTable);                                            //create namespace manager to use if necessary
            ns.AddNamespace("ns", "http://www.siemens.com/automation/Openness/SW/NetworkSource/FlgNet/v4");             //Add namespace for Node reference if necessary in XML file
            doc.Load(Methods.GetRelativePath(@"\Files\Xml\FC_AIn2oo3_Network.xml"));                                           //load doc from file                                                            //change value of a specific Node's Attibute 
            if (signal.isRedundant == "false")
            {
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit");                                             //pointer to a specific Node
                node.Attributes["ID"].Value = ID.ToString();
                node = doc.SelectSingleNode("//ns:Access[1]//ns:Component[1]", ns);//Inp_ValA
                node.Attributes["Name"].Value = signal.tagA;
                node = doc.SelectSingleNode("//ns:Access[1]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Val";
                node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[1]", ns);//Inp_ValB
                node.Attributes["Name"].Value = signal.tagB;
                node = doc.SelectSingleNode("//ns:Access[2]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Val";
                node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[1]", ns);//Inp_ValC
                node.Attributes["Name"].Value = signal.tagC;
                node = doc.SelectSingleNode("//ns:Access[3]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Val";
                node = doc.SelectSingleNode("//ns:Access[4]//ns:Component[1]", ns);//Cfg_PVEUMin
                node.Attributes["Name"].Value = "SETTINGS";
                node = doc.SelectSingleNode("//ns:Access[4]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[4]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "RANGE_L";
                node = doc.SelectSingleNode("//ns:Access[5]//ns:Component[1]", ns);//Cfg_PVEUMax
                node.Attributes["Name"].Value = "SETTINGS";
                node = doc.SelectSingleNode("//ns:Access[5]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[5]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "RANGE_H";
                node = doc.SelectSingleNode("//ns:Access[6]//ns:Component[1]", ns);//Inp_FailAlmA
                node.Attributes["Name"].Value = signal.tagA;
                node = doc.SelectSingleNode("//ns:Access[6]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Fail";
                node = doc.SelectSingleNode("//ns:Access[7]//ns:Component[1]", ns);//Inp_FailAlmB
                node.Attributes["Name"].Value = signal.tagB;
                node = doc.SelectSingleNode("//ns:Access[7]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Fail";
                node = doc.SelectSingleNode("//ns:Access[8]//ns:Component[1]", ns);//Inp_FailAlmC
                node.Attributes["Name"].Value = signal.tagC;
                node = doc.SelectSingleNode("//ns:Access[8]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Fail";
                node = doc.SelectSingleNode("//ns:Access[9]//ns:ConstantValue", ns);//Cfg_FailBypass
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[10]//ns:ConstantValue", ns);//Cfg_FailTripsUnit
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[11]//ns:ConstantValue", ns);//Cfg_FailResetRequired
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[12]//ns:ConstantValue", ns);//Cfg_InFailUsePVEUMax
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[13]//ns:ConstantValue", ns);//Cfg_InFailUsePVEUMin
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[14]//ns:ConstantValue", ns);//Cfg_InFailUseValSub
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[15]//ns:ConstantValue", ns);//Cfg_ValSub
                node.InnerText = "0.0";

                //-------------------------------------------------------------------------------------------------
                node = doc.SelectSingleNode("//ns:Access[16]//ns:Component[1]", ns);//Inp_HiHiAlmA
                node.Attributes["Name"].Value = signal.tagA;
                node = doc.SelectSingleNode("//ns:Access[16]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_HiHi";
                node = doc.SelectSingleNode("//ns:Access[17]//ns:Component[1]", ns);//Inp_HiHiAlmB
                node.Attributes["Name"].Value = signal.tagB;
                node = doc.SelectSingleNode("//ns:Access[17]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_HiHi";
                node = doc.SelectSingleNode("//ns:Access[18]//ns:Component[1]", ns);//Inp_HiHiAlmC
                node.Attributes["Name"].Value = signal.tagC;
                node = doc.SelectSingleNode("//ns:Access[18]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_HiHi";
                node = doc.SelectSingleNode("//ns:Access[19]//ns:ConstantValue", ns);//Cfg_HasHiHiAlm
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[20]//ns:Component[1]", ns);//Oset_HiHiLim
                node.Attributes["Name"].Value = "SETTINGS";
                node = doc.SelectSingleNode("//ns:Access[20]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[20]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "SP_HH";
                node = doc.SelectSingleNode("//ns:Access[21]//ns:ConstantValue", ns);//Cfg_HiHiDelay
                node.InnerText = "T#1s";
                node = doc.SelectSingleNode("//ns:Access[22]//ns:ConstantValue", ns);//Cfg_HiHiDB
                node.InnerText = "0.0";
                node = doc.SelectSingleNode("//ns:Access[23]//ns:ConstantValue", ns);//Cfg_HiHiBypass
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[24]//ns:ConstantValue", ns);//Cfg_HiHiTripsUnit
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[25]//ns:ConstantValue", ns);//Cfg_HiHiResetRequired
                node.InnerText = "false";

                //-------------------------------------------------------------------------------------------------
                node = doc.SelectSingleNode("//ns:Access[26]//ns:Component[1]", ns);//Inp_HiAlmA
                node.Attributes["Name"].Value = signal.tagA;
                node = doc.SelectSingleNode("//ns:Access[26]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Hi";
                node = doc.SelectSingleNode("//ns:Access[27]//ns:Component[1]", ns);//Inp_HiAlmB
                node.Attributes["Name"].Value = signal.tagB;
                node = doc.SelectSingleNode("//ns:Access[27]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Hi";
                node = doc.SelectSingleNode("//ns:Access[28]//ns:Component[1]", ns);//Inp_HiAlmC
                node.Attributes["Name"].Value = signal.tagC;
                node = doc.SelectSingleNode("//ns:Access[28]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Hi";
                node = doc.SelectSingleNode("//ns:Access[29]//ns:ConstantValue", ns);//Cfg_HasHiAlm
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[30]//ns:Component[1]", ns);//Oset_HiLim
                node.Attributes["Name"].Value = "SETTINGS";
                node = doc.SelectSingleNode("//ns:Access[30]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[30]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "SP_H";
                node = doc.SelectSingleNode("//ns:Access[31]//ns:ConstantValue", ns);//Cfg_HiDelay
                node.InnerText = "T#1s";
                node = doc.SelectSingleNode("//ns:Access[32]//ns:ConstantValue", ns);//Cfg_HiDB
                node.InnerText = "0.0";
                node = doc.SelectSingleNode("//ns:Access[33]//ns:ConstantValue", ns);//Cfg_HiBypass
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[34]//ns:ConstantValue", ns);//Cfg_HiResetRequired
                node.InnerText = "false";
                //-------------------------------------------------------------------------------------------------

                node = doc.SelectSingleNode("//ns:Access[35]//ns:Component[1]", ns);//Inp_LoAlmA
                node.Attributes["Name"].Value = signal.tagA;
                node = doc.SelectSingleNode("//ns:Access[35]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Lo";
                node = doc.SelectSingleNode("//ns:Access[36]//ns:Component[1]", ns);//Inp_LoAlmB
                node.Attributes["Name"].Value = signal.tagB;
                node = doc.SelectSingleNode("//ns:Access[36]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Lo";
                node = doc.SelectSingleNode("//ns:Access[37]//ns:Component[1]", ns);//Inp_LoAlmC
                node.Attributes["Name"].Value = signal.tagC;
                node = doc.SelectSingleNode("//ns:Access[37]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_Lo";
                node = doc.SelectSingleNode("//ns:Access[38]//ns:ConstantValue", ns);//Cfg_HasLoAlm
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[39]//ns:Component[1]", ns);//Oset_LoLim
                node.Attributes["Name"].Value = "SETTINGS";
                node = doc.SelectSingleNode("//ns:Access[39]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[39]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "SP_L";
                node = doc.SelectSingleNode("//ns:Access[40]//ns:ConstantValue", ns);//Cfg_LoDelay
                node.InnerText = "T#1s";
                node = doc.SelectSingleNode("//ns:Access[41]//ns:ConstantValue", ns);//Cfg_LoDB
                node.InnerText = "0.0";
                node = doc.SelectSingleNode("//ns:Access[42]//ns:ConstantValue", ns);//Cfg_LoBypass
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[43]//ns:ConstantValue", ns);//Cfg_LoResetRequired
                node.InnerText = "false";
                //-------------------------------------------------------------------------------------------------

                node = doc.SelectSingleNode("//ns:Access[44]//ns:Component[1]", ns);//Inp_LoLoAlmA
                node.Attributes["Name"].Value = signal.tagA;
                node = doc.SelectSingleNode("//ns:Access[44]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_LoLo";
                node = doc.SelectSingleNode("//ns:Access[45]//ns:Component[1]", ns);//Inp_LoLoAlmB
                node.Attributes["Name"].Value = signal.tagB;
                node = doc.SelectSingleNode("//ns:Access[45]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_LoLo";
                node = doc.SelectSingleNode("//ns:Access[46]//ns:Component[1]", ns);//Inp_LoLoAlmC
                node.Attributes["Name"].Value = signal.tagC;
                node = doc.SelectSingleNode("//ns:Access[46]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = "Alm_LoLo";
                node = doc.SelectSingleNode("//ns:Access[47]//ns:ConstantValue", ns);//Cfg_HasLoLoAlm
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[48]//ns:Component[1]", ns);//Oset_LoLoLim
                node.Attributes["Name"].Value = "SETTINGS";
                node = doc.SelectSingleNode("//ns:Access[48]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//ns:Access[48]//ns:Component[3]", ns);
                node.Attributes["Name"].Value = "SP_LL";
                node = doc.SelectSingleNode("//ns:Access[49]//ns:ConstantValue", ns);//Cfg_LoLoDelay
                node.InnerText = "T#1s";
                node = doc.SelectSingleNode("//ns:Access[50]//ns:ConstantValue", ns);//Cfg_LoLoDB
                node.InnerText = "0.0";
                node = doc.SelectSingleNode("//ns:Access[51]//ns:ConstantValue", ns);//Cfg_LoLoBypass
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[52]//ns:ConstantValue", ns);//Cfg_LoLoTripsUnit
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[53]//ns:ConstantValue", ns);//Cfg_LoLoResetRequired
                node.InnerText = "false";
                //---------------------------------------------------------------------------------------------
                
                node = doc.SelectSingleNode("//ns:Access[54]//ns:ConstantValue", ns);//Cfg_CheckPercDev
                node.InnerText = "true";
                node = doc.SelectSingleNode("//ns:Access[55]//ns:ConstantValue", ns);//Cfg_CheckEUDev
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[56]//ns:ConstantValue", ns);//Cfg_EUDeviation
                node.InnerText = "0.0";
                node = doc.SelectSingleNode("//ns:Access[57]//ns:ConstantValue", ns);//Cfg_PercDeviation
                node.InnerText = "5.0";
                node = doc.SelectSingleNode("//ns:Access[58]//ns:Component[1]", ns);//Inp_Reset
                node.Attributes["Name"].Value = settings.tagReset;
                node = doc.SelectSingleNode("//ns:Access[59]//ns:ConstantValue", ns);//PCmd_MOS
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[60]//ns:ConstantValue", ns);//Cfg_UseDigitalAlarms
                node.InnerText = "true";
                node = doc.SelectSingleNode("//ns:Access[61]//ns:ConstantValue", ns);//Cfg_UseMedianValue
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[62]//ns:ConstantValue", ns);//Cfg_if1FailUse2oo2
                node.InnerText = "false";
                node = doc.SelectSingleNode("//ns:Access[63]//ns:ConstantValue", ns);//SpareIn1
                node.InnerText = "0.0";
                node = doc.SelectSingleNode("//ns:Access[64]//ns:ConstantValue", ns);//SpareIn2
                node.InnerText = "0.0";
                node = doc.SelectSingleNode("//ns:Access[65]//ns:Component[1]", ns);//CommonFirstOut
                node.Attributes["Name"].Value = settings.tagCmnFo;
                node = doc.SelectSingleNode("//ns:Access[66]//ns:Component[1]", ns);//IsaAlarmFlashing
                node.Attributes["Name"].Value = "UP";
                node = doc.SelectSingleNode("//ns:Access[66]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = settings.tagAlmFlash;
                node = doc.SelectSingleNode("//ns:Access[67]//ns:Component[1]", ns);//IsaTripFlashing
                node.Attributes["Name"].Value = "UP";
                node = doc.SelectSingleNode("//ns:Access[67]//ns:Component[2]", ns);
                node.Attributes["Name"].Value = settings.tagTripFlash;
                //---------------------------------------------------------------------------------------------

                if (signal.hasHiHi == "true" || (signal.hasHi == "true" && signal.hasLoLo == "false"))
                {
                    node = doc.SelectSingleNode("//ns:Access[12]//ns:ConstantValue", ns);//Cfg_InFailUsePVEUMax
                    node.InnerText = "true";
                }

                if (!(signal.hasHiHi == "true" || (signal.hasHi == "true" && signal.hasLoLo == "false")))
                {
                    node = doc.SelectSingleNode("//ns:Access[13]//ns:ConstantValue", ns);//Cfg_InFailUsePVEUMax
                    node.InnerText = "true";
                }
                if (signal.description.ToLower().Contains("temperature"))
                {
                    node = doc.SelectSingleNode("//ns:Access[21]//ns:ConstantValue", ns);//cfg_HiHiDelay
                    node.InnerText = "T#5s";
                    node = doc.SelectSingleNode("//ns:Access[31]//ns:ConstantValue", ns);//cfg_HiDelay
                    node.InnerText = "T#5s";
                    node = doc.SelectSingleNode("//ns:Access[40]//ns:ConstantValue", ns);//cfg_LoDelay
                    node.InnerText = "T#5s";
                    node = doc.SelectSingleNode("//ns:Access[49]//ns:ConstantValue", ns);//cfg_LoLoDelay
                    node.InnerText = "T#5s";
                }
                if (signal.FailTrips == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[10]//ns:ConstantValue", ns);//cfg_FailTripsUnit
                    node.InnerText = "true";
                }
                if (signal.HiHiTrips == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[24]//ns:ConstantValue", ns);//cfg_HiHiTripsUnit
                    node.InnerText = "true";
                }
                if (signal.LoLoTrips == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[52]//ns:ConstantValue", ns);//cfg_LoLoTripsUnit
                    node.InnerText = "true";
                }
                if (signal.hasHiHi == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[19]//ns:ConstantValue", ns);//cfg_HasHiHiAlm
                    node.InnerText = "true";
                }
                if (signal.hasHi == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[29]//ns:ConstantValue", ns);//cfg_HasHiAlm
                    node.InnerText = "true";
                }
                if (signal.hasLo == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[38]//ns:ConstantValue", ns);//cfg_HasLoAlm
                    node.InnerText = "true";
                }
                if (signal.hasLoLo == "true")
                {
                    node = doc.SelectSingleNode("//ns:Access[47]//ns:ConstantValue", ns);//cfg_HasLoLoAlm
                    node.InnerText = "true";
                }

                //NETWORK FOOTER
                node = doc.SelectSingleNode("//ns:Call//ns:Component", ns);
                node.Attributes["Name"].Value = signal.tag;
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]");
                node.Attributes["ID"].Value = "A" + ID.ToString();
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[1]//MultilingualTextItem");
                node.Attributes["ID"].Value = "B" + ID.ToString();
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]");
                node.Attributes["ID"].Value = "C" + ID.ToString();
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem");
                node.Attributes["ID"].Value = "D" + ID.ToString();
                node = doc.SelectSingleNode("//SW.Blocks.CompileUnit//MultilingualText[2]//MultilingualTextItem//Text");
                node.InnerText = signal.description;
            }
            xml += "\n" + doc.OuterXml;
        }
    }
}

